# Read the Docs configuration file
# Details: https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

# Documentation build configuration -------------
# Using sphinx
sphinx:
  configuration: docs/conf.py
# Additional output formats (Optional)
#formats:
#  - pdf

# Build configuration ---------------------------
# System settings
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
# Python settings
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
