[tool.poetry]
version = "0.1.0"
name = "embutils"
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/cwichel/embutils"
description = "Python utilities for embedded projects"
authors = ["Christian Wiche <cwichel@gmail.com>"]
keywords = [
    'python',
    'embedded',
    'utilities'
    ]
classifiers = [
    'License :: OSI Approved :: MIT License',
    'Operating System :: Microsoft :: Windows',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Topic :: Utilities',
    ]

[tool.poetry.scripts]
test    = 'scripts.poetry:poetry_test'
version = 'scripts.poetry:poetry_version'

[tool.poetry.dependencies]
python = "^3.8"
pyserial = "^3.5"
pynput = "^1.7.3"
PyGetWindow = "^0.0.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
toml = "^0.10.2"
GitPython = "^3.1.17"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
