name:   ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os:   [ windows-latest ]
        env:  [ 3.6, 3.7, 3.8, 3.9 ]

    runs-on:  ${{ matrix.os }}

    steps:
    - name:   Checkout repository
      uses:   actions/checkout@master

    - name:   Setup python environment
      uses:   actions/setup-python@master
      with:
        python-version: ${{ matrix.env }}

    - name:   Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8
        pip install -r requirements.txt

    - name:   Check code syntax
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name:   Install package
      run:  |
        python setup.py install

    - name:   Run tests
      run:  |
        pytest
