# Action ----------------------------------------
name:   ci

# When / Over what execute action ---------------
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# What to do when triggered ---------------------
jobs:
  # Build job: Generate environment and run tests
  build:
    strategy:
      matrix:
        os:   [ windows-latest ]
        env:  [ 3.7, 3.8, 3.9 ]

    # Prepare machine
    runs-on:  ${{ matrix.os }}

    steps:
    # Get the latest main branch
    - name:   Checkout repository
      uses:   actions/checkout@master

    # Prepare the python environment
    - name:   Setup python environment
      uses:   actions/setup-python@master
      with:
        python-version: ${{ matrix.env }}

    - name:   Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8
        pip install -r requirements.txt

    # Check code
    - name:   Check code syntax
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Install package to run tests
    - name:   Install package
      run:  |
        python setup.py install

    # Run tests
    - name:   Run tests
      run:  |
        pytest
